name: Build and Deploy to main

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Copy dist to root (overwrite main)
        run: |
          rm -rf * !(dist)  # Удаляем всё, кроме папки dist
          mv dist/* .         # Перемещаем содержимое dist в корень
          rmdir dist          # Удаляем пустую папку dist

      - name: Commit and push back to main
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: deploy built site"
          branch: main
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
